"""empty message

Revision ID: 722cc6f79680
Revises: a4c1654ad3da
Create Date: 2019-09-19 17:14:12.379547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722cc6f79680'
down_revision = 'a4c1654ad3da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
