"""empty message

Revision ID: d27126d961c1
Revises: 054e27fde229
Create Date: 2019-09-17 15:39:29.133791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd27126d961c1'
down_revision = '054e27fde229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('description', sa.String(), nullable=False))
    op.drop_column('posts', 'decription')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('decription', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('posts', 'description')
    # ### end Alembic commands ###
